config/routes.rb
NpCompleteHeart::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :roles

  devise_for :users, :controllers => { :registrations => "users/registrations" }

  resources :posts do
    resources :comments
  end
  
  
  resources :about
  
  resources :contact

  root :to => "posts#front"

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
    user ||= User.new # guest user
 
    if user.role? :Admin
      can :manage, :all
    else
       can :read, :all
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    validates :name,  :presence => true
    validates :title, :presence => true,
                      :length => { :minimum => 5 }
    has_many :comments, :dependent => :destroy
    has_many :tags

    accepts_nested_attributes_for :tags, :allow_destroy => :true,
        :reject_if => proc { |attrs| attrs.all? { |k,v| v.blank?} }
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :roles
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  
  def role?(role)
     return !!self.roles.find_by_name(role.to_s.camelize)
   end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @title='About'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = exception.message
    redirect_to root_url
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(params[:comment])
        redirect_to post_path(@post)
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @title='Contact'
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :authenticate_user!, :except => [:front, :index, :show]
  
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all.reverse

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end
  
  def front
    @posts = Post.all.reverse[0,3]
    
    respond_to do |format|
      format.html
      format.xml { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    authorize! :edit, @post
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    authorize! :create, @post
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    authorize! :update, @article
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    authorize! :destroy, @article
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  # GET /roles
  # GET /roles.xml
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.xml
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.xml
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.xml
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to(@role, :notice => 'Role was successfully created.') }
        format.xml  { render :xml => @role, :status => :created, :location => @role }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @role.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.xml
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to(@role, :notice => 'Role was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @role.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.xml
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to(roles_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :check_permissions, :only => [:new, :create, :cancel]
  skip_before_filter :require_no_authentication
 
  def check_permissions
    authorize! :create, resource
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def join_tags(post)
        post.tags.map { |t| t.name }.join(", ")
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/about/index.html.erb
<p>Data analyst, programming hack, and a (moderately) reformed biologist; this is my place to share what I come across, a bit of what I'm doing, and a fun grab bag of anything else. </p>
<p>In all honesty though, outside of the obligatory cat pictures you can expect that this will be my place to talk about code, languages, computers, and the other parts that I deal with daily.  Hopefully it will be useful, maybe not, but nonetheless here it is.</p>
<p>Otherwise, as a fair warning, I'm a heavy vi user, spend most of my time on the command line, write in python, and am frequently confused by GUIs.  Outside of that I'm generally interested in mathematics, technology, and proper analysis of the data that we all swim in.</p>
<p>As for myself, I'm a <a href="http://amaral-lab.org/people/pah">graduate student</a> at Northwestern University, conducting my doctoral research in the Amaral Laboratory. My research is biologically focused for the most part, but I take many steps and projects outside of that domain. Also, due to my current position, I have many opinions about biology, graduate school, academic research, and other related topics that may creep into this blog.</p>

app/views/comments/_comment.html.erb
<p>
  <b>Commenter:</b> 
  <%= comment.commenter %><br />
  <%= comment.body %>
</p>

<% if user_signed_in?%>
<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               :confirm => 'Are you sure?',
               :method => :delete %>
</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contact/index.html.erb
<center>
<p><a href='mailto:npcompleteheart@gmail.com'> npcompleteheart at gmail dot com</a></p>
<!-- <%= link_to image_tag("google-plus-3-icon.png"), "http://plus.google.com/117549740272673061302/" %> -->
<%= link_to image_tag("twitter.png"), "http://www.twitter.com/adamrpah" %>
<%= link_to image_tag("linked_in.png"), "http://www.linkedin.com/in/adampah/" %>
<br />
<%= link_to image_tag("GitHub_Icon.png"), "http://www.github.com/adamrpah/"%>
<%= link_to image_tag("Bitbucket.png"), "http://www.bitbucket.org/adamrpah/"%>
</center>

app/views/layouts/_header.html.erb
<header>
	<ul>
		<li><%= link_to image_tag("logo.png", :alt => "NP Complete Heart"), root_url%></li>
		<li>
		<nav>
			<ul>
				<li><%=link_to "Home", root_url%></li>
		  		<li><%= link_to "Archive", posts_path %></li>
		  		<li><%= link_to "About", :controller => "/about", :action => "index" %></li>
		  		<li><%= link_to "Contact", :controller => "/contact", :action => "index" %></li>
			</ul>
		</nav>
		</li>
	</ul>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<!-- <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %> -->
<!-- <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %> -->
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NP Complete Heart | <%= @title %></title>
	<META NAME="Author" CONTENT="Adam R Pah, npcompleteheart@gmail.com">
    <%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets'%>
	<%= javascript_include_tag :all %>
	<script type="text/javascript">
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-24774016-1']);
	  _gaq.push(['_trackPageview']);
	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	</script>
	<script type="text/javascript" charset="utf-8">
		function showcomment() {
			var hiddenDiv = document.getElementById('hidden');
			hiddenDiv.style.display = 'block';
		}
	</script>
  </head> 
<body style>
<body onload="prettyPrint()">
	<div class="container">
		<section class="round">
  		<%= render 'layouts/header'%>
		</section>
	</div>
	<div class ="container">
		<section class = "round">
	    <%= yield %>
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
		</section>
	</div>
  </body>
</html>

app/views/posts/_form.html.erb
<% @post.tags.build %>
<%= form_for(@post) do |post_form| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="field">
    <%= post_form.label :name %><br />
    <%= post_form.text_field :name %>
  </div>
  <div class="field">
    <%= post_form.label :title %><br />
    <%= post_form.text_field :title %>
  </div>
  <div class="field">
    <%= post_form.label :content %><br />
    <%= post_form.text_area :content %>
  </div>
  <h2>Tags</h2>
  <%= render :partial => 'tags/form',
             :locals => {:form => post_form} %>
  <div class="actions">
    <%= post_form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/front.html.erb
<% @posts.each do |post|%>
	<p>
		<strong><%= link_to post.title, post%></strong>
		<font size=-1pt>
		  <%=post.created_at.month.to_s+'.'+post.created_at.day.to_s+'.'+post.created_at.year.to_s%>
		</font>
		<br />
		<%=post.content.split[0,200].join(' ').html_safe%>
		<% if post.content.split.length>200 %>
			<%= link_to "... (Read more)", post %>
		<% end %>
		<br />
	</p>
<% end %>
<p><%= link_to "More Articles...", posts_path%>

app/views/posts/index.html.erb
<table>
<% @posts.each do |post| %>
  <tr>
	<%@post_time=post.created_at.month.to_s+'.'+post.created_at.day.to_s+'.'+post.created_at.year.to_s%>
	<td><%= link_to @post_time, post%></td>
    <td><%= link_to post.title, post %></td>
	<% if user_signed_in? %>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
	<%end%>
  </tr>
<% end %>
</table>

<br />

<% if user_signed_in?%>
<%= link_to 'New Post', new_post_path %>
<%end%>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <h3><%= @post.title %></h3>
</p>

<p>
  <%= @post.content.html_safe %>
</p>

<!-- <p>
  <b>Tags:</b>
  <%= join_tags(@post)%>
</p> -->
<% if user_signed_in?%>
  <%= link_to 'Edit Post', edit_post_path(@post) %>
<% end %>

<%= image_tag("articlefooter.png", :alt => "article_footer") %>

<% if @post.comments %>
  <%= render @post.comments %>
<% else %>
  <h4>No Comments, be the first!</h4>
<% end %>

<a class="button" href="#" id="show" onclick="showcomment();return false;">Add Comment</a>
<div id="hidden" style="display:none">
	<br /><br />
	<%= render "comments/form" %>
</div>

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% for role in Role.find(:all) %>
    <div>
      <%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role) %>
      <%= role.name %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1>Listing roles</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roles.each do |role| %>
  <tr>
    <td><%= role.name %></td>
    <td><%= link_to 'Show', role %></td>
    <td><%= link_to 'Edit', edit_role_path(role) %></td>
    <td><%= link_to 'Destroy', role, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @role.name %>
</p>


<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/tags/_form.html.erb
<%= form.fields_for :tags do |tag_form| %>
  <div class="field">
    <%= tag_form.label :name, 'Tag:' %>
    <%= tag_form.text_field :name %>
  </div>
  <% unless tag_form.object.nil? || tag_form.object.new_record? %>
    <div class="field">
      <%= tag_form.label :_destroy, 'Remove:' %>
      <%= tag_form.check_box :_destroy %>
    </div>
  <% end %>
<% end %>